require(unixtools)
path<-tempdir()
system(paste("rm -rf ", "Rtmp*",path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("tinytex", repos="https://cloud.r-project.org/")
tinytex::install_tinytex()
install.packages("rvest", repos="https://cloud.r-project.org/")
install.packages("devtools", repos="https://cloud.r-project.org/")
devtools::install_github("s-u/unixtools")
install.packages("reticulate", repos="https://cloud.r-project.org/")
install.packages("tensorflow", repos="https://cloud.r-project.org/")
#tensorflow::install_tensorflow(version = "2.0.0")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")


install.packages("keras", repos="https://cloud.r-project.org/")
#keras::install_keras()
install.packages("Rcpp", repos="https://cloud.r-project.org/")
install.packages("tidyr", repos="https://cloud.r-project.org/")
install.packages("leaflet", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("lubridate", repos="https://cloud.r-project.org/")
install.packages("rmarkdown", repos="https://cloud.r-project.org/")
install.packages("hexbin", repos="https://cloud.r-project.org/")
install.packages("penalized", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")


install.packages("httr", repos="https://cloud.r-project.org/")
install.packages("httpuv", repos="https://cloud.r-project.org/")
install.packages("DT", repos="https://cloud.r-project.org/")
install.packages("magrittr", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("ggplot2", repos="https://cloud.r-project.org/")
install.packages("gridExtra", repos="https://cloud.r-project.org/")
install.packages("bitops", repos="https://cloud.r-project.org/")
install.packages("reactable", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("remotes", repos="https://cloud.r-project.org/")
install.packages("shiny", repos="https://cloud.r-project.org/")
install.packages("knitr", repos="https://cloud.r-project.org/")
install.packages("sparklyr", repos="https://cloud.r-project.org/")
sparklyr::spark_install()

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")


install.packages("tfautograph", repos="https://cloud.r-project.org/")
install.packages("nycflights13", repos="https://cloud.r-project.org/")
install.packages("Lahman", repos="https://cloud.r-project.org/")
install.packages("rsparkling", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("h2o", repos="https://cloud.r-project.org/")
install.packages("rscala", repos="https://cloud.r-project.org/")
install.packages("shinydashboard", repos="https://cloud.r-project.org/")
install.packages("learnr", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("here", repos="https://cloud.r-project.org/")
install.packages("ctv", repos="https://cloud.r-project.org/")
install.packages("evtree", repos="https://cloud.r-project.org/")
install.packages("mokken", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("lvnet", repos="https://cloud.r-project.org/")
install.packages("randomForestSRC", repos="https://cloud.r-project.org/")
install.packages("GeneNet", repos="https://cloud.r-project.org/")
install.packages("sna", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("abc", repos="https://cloud.r-project.org/")
install.packages("radiant", repos="https://cloud.r-project.org/")
install.packages("radiant.data", repos="https://cloud.r-project.org/")
install.packages("radiant.design", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("radiant.basics", repos="https://cloud.r-project.org/")
install.packages("radiant.model", repos="https://cloud.r-project.org/")
install.packages("radiant.multivariate", repos="https://cloud.r-project.org/")
install.packages("rcc", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("RGCCA", repos="https://cloud.r-project.org/")
install.packages("ggquickeda", repos="https://cloud.r-project.org/")
install.packages("openintro", repos="https://cloud.r-project.org/")
install.packages("effects", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("Rborist", repos="https://cloud.r-project.org/")
install.packages("rbartMachine", repos="https://cloud.r-project.org/")
devtools::install_github("sachsmc/ggkm")
devtools::install_github("benjaminrich/table1")
devtools::install_github("slowkow/ggrepel")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("hdi", repos="https://cloud.r-project.org/")
install.packages("tfplot", repos="https://cloud.r-project.org/")
install.packages("ranger", repos="https://cloud.r-project.org/")
install.packages("purr", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("tfruns", repos="https://cloud.r-project.org/")
install.packages("tfprobability", repos="https://cloud.r-project.org/")
install.packages("tframe", repos="https://cloud.r-project.org/")
install.packages("reticulate", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("tfestimators", repos="https://cloud.r-project.org/")
install.packages("sem", repos="https://cloud.r-project.org/")
install.packages("glmnet", repos="https://cloud.r-project.org/")
install.packages("mirt", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("BayesTree", repos="https://cloud.r-project.org/")
install.packages("BayesTreePrior", repos="https://cloud.r-project.org/")
install.packages("mlpack", repos="https://cloud.r-project.org/")
install.packages("mboost", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("readr", repos="https://cloud.r-project.org/")
install.packages("callr", repos="https://cloud.r-project.org/")
install.packages("jpeg", repos="https://cloud.r-project.org/")
install.packages("lavaan", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("blavaan", repos="https://cloud.r-project.org/")
install.packages("semTools", repos="https://cloud.r-project.org/")
install.packages("ipred", repos="https://cloud.r-project.org/")
install.packages("rprojroot", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("ipred", repos="https://cloud.r-project.org/")
install.packages("wsrf", repos="https://cloud.r-project.org/")
install.packages("ergm", repos="https://cloud.r-project.org/")
install.packages("np", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("lasso2", repos="https://cloud.r-project.org/")
install.packages("lars", repos="https://cloud.r-project.org/")
install.packages("DescTools", repos="https://cloud.r-project.org/")
install.packages("MCMCpack", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("caTools", repos="https://cloud.r-project.org/")
install.packages("mlr3", repos="https://cloud.r-project.org/")
install.packages("mlr3benchmark", repos="https://cloud.r-project.org/")
install.packages("mlr3cluster", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("mlr3data", repos="https://cloud.r-project.org/")
install.packages("mlr3db", repos="https://cloud.r-project.org/")
install.packages("mlr3filters", repos="https://cloud.r-project.org/")
install.packages("mlr3fselect", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("mlr3hyperband", repos="https://cloud.r-project.org/")
install.packages("mlr3learners", repos="https://cloud.r-project.org/")
install.packages("mlr3measures", repos="https://cloud.r-project.org/")
install.packages("mlr3misc", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("mlr3oml", repos="https://cloud.r-project.org/")
install.packages("mlr3pipelines", repos="https://cloud.r-project.org/")
install.packages("mlr3poba", repos="https://cloud.r-project.org/")
install.packages("mlr3shiny", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("mlr3spatiotempcv", repos="https://cloud.r-project.org/")
install.packages("mlr3tuning", repos="https://cloud.r-project.org/")
install.packages("mlr3verse", repos="https://cloud.r-project.org/")
install.packages("mlr3viz", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("ahaz" , repos="https://cloud.r-project.org/")
install.packages("arules", repos="https://cloud.r-project.org/")
install.packages("BART", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("bartMachine", repos="https://cloud.r-project.org/")
install.packages("BayesTree", repos="https://cloud.r-project.org/")
install.packages("BDgraph", repos="https://cloud.r-project.org/")
install.packages("biglasso", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("bmrm", repos="https://cloud.r-project.org/")
install.packages("Boruta", repos="https://cloud.r-project.org/")
install.packages("bst", repos="https://cloud.r-project.org/")
install.packages("C50", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("caret", repos="https://cloud.r-project.org/")
install.packages("CORElearn", repos="https://cloud.r-project.org/")
install.packages("Cubist", repos="https://cloud.r-project.org/")
install.packages("deepnet", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("DoubleML", repos="https://cloud.r-project.org/")
install.packages("e1071", repos="https://cloud.r-project.org/")
install.packages("earth", repos="https://cloud.r-project.org/")
install.packages("effects", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("elasticnet", repos="https://cloud.r-project.org/")
install.packages("evclass", repos="https://cloud.r-project.org/")
install.packages("frbs", repos="https://cloud.r-project.org/")
install.packages("gamboostLSS", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("gbm", repos="https://cloud.r-project.org/")
install.packages("ggRandomForests", repos="https://cloud.r-project.org/")
install.packages("glmnet", repos="https://cloud.r-project.org/")
install.packages("glmpath", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("GMMBoost", repos="https://cloud.r-project.org/")
install.packages("gradDescent", repos="https://cloud.r-project.org/")
install.packages("grf", repos="https://cloud.r-project.org/")
install.packages("grplasso", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("grpreg", repos="https://cloud.r-project.org/")
install.packages("hda", repos="https://cloud.r-project.org/")
install.packages("hdi", repos="https://cloud.r-project.org/")
install.packages("hdm", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("ICEbox", repos="https://cloud.r-project.org/")
install.packages("kernlab", repos="https://cloud.r-project.org/")
install.packages("klaR", repos="https://cloud.r-project.org/")
install.packages("LiblineaR", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("lightgbm", repos="https://cloud.r-project.org/")
install.packages("maptree", repos="https://cloud.r-project.org/")
install.packages("mlpack", repos="https://cloud.r-project.org/")
install.packages("naivebayes", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("ncvreg", repos="https://cloud.r-project.org/")
install.packages("nnet", repos="https://cloud.r-project.org/")
install.packages("OneR", repos="https://cloud.r-project.org/")
install.packages("opusminer", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("pamr", repos="https://cloud.r-project.org/")
install.packages("party", repos="https://cloud.r-project.org/")
install.packages("partykit", repos="https://cloud.r-project.org/")
install.packages("pdp", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("penalized", repos="https://cloud.r-project.org/")
install.packages("penalizedLDA", repos="https://cloud.r-project.org/")
install.packages("picasso", repos="https://cloud.r-project.org/")
install.packages("plotmo", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("quantregForest", repos="https://cloud.r-project.org/")
install.packages("randomForest", repos="https://cloud.r-project.org/")
install.packages("randomForestSRC", repos="https://cloud.r-project.org/")
install.packages("missRanger", repos="https://cloud.r-project.org/")
install.packages("rattle", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("Rborist", repos="https://cloud.r-project.org/")
install.packages("RcppDL", repos="https://cloud.r-project.org/")
install.packages("rdetools", repos="https://cloud.r-project.org/")
install.packages("relaxo", repos="https://cloud.r-project.org/")
install.packages("rgenoud", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("RGF", repos="https://cloud.r-project.org/")
install.packages("RLT", repos="https://cloud.r-project.org/")
install.packages("Rmalschains", repos="https://cloud.r-project.org/")
install.packages("rminer", repos="https://cloud.r-project.org/")
install.packages("ROCR", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("RoughSets", repos="https://cloud.r-project.org/")
install.packages("rpart", repos="https://cloud.r-project.org/")
install.packages("RPMM", repos="https://cloud.r-project.org/")
install.packages("RSNNS", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("RWeka", repos="https://cloud.r-project.org/")
install.packages("RXshrink", repos="https://cloud.r-project.org/")
install.packages("sda", repos="https://cloud.r-project.org/")
install.packages("SIS", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("splitTools", repos="https://cloud.r-project.org/")
install.packages("ssgraph", repos="https://cloud.r-project.org/")
install.packages("stabs", repos="https://cloud.r-project.org/")
install.packages("SuperLearner", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("svmpath", repos="https://cloud.r-project.org/")
install.packages("tgp", repos="https://cloud.r-project.org/")
install.packages("torch", repos="https://cloud.r-project.org/")
install.packages("tree", repos="https://cloud.r-project.org/")

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages("trtf", repos="https://cloud.r-project.org/")
install.packages("varSelRF", repos="https://cloud.r-project.org/")
install.packages("wsrf", repos="https://cloud.r-project.org/")
install.packages("xgboost", repos="https://cloud.r-project.org/")
 
require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('AER',repos='https://cloud.r -project.org/')
install.packages('ARCensReg',repos='https://cloud.r -project.org/')
install.packages('ArDec',repos='https://cloud.r -project.org/')
install.packages('arfima',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('ASSA',repos='https://cloud.r -project.org/')
install.packages('astsa',repos='https://cloud.r -project.org/')
install.packages('autostsm',repos='https://cloud.r -project.org/')
install.packages('BayesARIMAX',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('bayesforecast',repos='https://cloud.r -project.org/')
install.packages('BAYSTAR',repos='https://cloud.r -project.org/')
install.packages('bentcableAR',repos='https://cloud.r -project.org/')
install.packages('BETS',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('bfast',repos='https://cloud.r -project.org/')
install.packages('bigtime',repos='https://cloud.r -project.org/')
install.packages('BigVAR',repos='https://cloud.r -project.org/')
install.packages('biwavelet',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('blocklength',repos='https://cloud.r -project.org/')
install.packages('BMTAR',repos='https://cloud.r -project.org/')
install.packages('BNPTSclust',repos='https://cloud.r -project.org/')
install.packages('boot',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('BootPR',repos='https://cloud.r -project.org/')
install.packages('bootUR',repos='https://cloud.r -project.org/')
install.packages('breakfast',repos='https://cloud.r -project.org/')
install.packages('bspec',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('bssm',repos='https://cloud.r -project.org/')
install.packages('bsts',repos='https://cloud.r -project.org/')
install.packages('bundesbank',repos='https://cloud.r -project.org/')
install.packages('BVAR',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('bvartools',repos='https://cloud.r -project.org/')
install.packages('CADFtest',repos='https://cloud.r -project.org/')
install.packages('carfima',repos='https://cloud.r -project.org/')
install.packages('carx',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('changepoint',repos='https://cloud.r -project.org/')
install.packages('changepoint.geo',repos='https://cloud.r -project.org/')
install.packages('changepoint.mv',repos='https://cloud.r -project.org/')
install.packages('changepoint.np',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('chron',repos='https://cloud.r -project.org/')
install.packages('clock',repos='https://cloud.r -project.org/')
install.packages('cointReg',repos='https://cloud.r -project.org/')
install.packages('collapse',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")


install.packages('costat',repos='https://cloud.r -project.org/')
install.packages('data.table',repos='https://cloud.r -project.org/')
install.packages('dataseries',repos='https://cloud.r -project.org/')
install.packages('DChaos',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('dCovTS',repos='https://cloud.r -project.org/')
install.packages('depmix',repos='https://cloud.r -project.org/')
install.packages('depmixS4',repos='https://cloud.r -project.org/')
install.packages('deseasonalize',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('diffusion',repos='https://cloud.r -project.org/')
install.packages('disaggR',repos='https://cloud.r -project.org/')
install.packages('dLagM',repos='https://cloud.r -project.org/')
install.packages('dlm',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('dlnm',repos='https://cloud.r -project.org/')
install.packages('dsa',repos='https://cloud.r -project.org/')
install.packages('dse',repos='https://cloud.r -project.org/')
install.packages('DTSg',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('dtw',repos='https://cloud.r -project.org/')
install.packages('dtwclust',repos='https://cloud.r -project.org/')
install.packages('dygraphs',repos='https://cloud.r -project.org/')
install.packages('dyn',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('dynlm',repos='https://cloud.r -project.org/')
install.packages('dynr',repos='https://cloud.r -project.org/')
install.packages('earlywarnings',repos='https://cloud.r -project.org/')
install.packages('EBMAforecast',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('Ecdat',repos='https://cloud.r -project.org/')
install.packages('ecm',repos='https://cloud.r -project.org/')
install.packages('ecp',repos='https://cloud.r -project.org/')
install.packages('EMD',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('ensembleBMA',repos='https://cloud.r -project.org/')
install.packages('expsmooth',repos='https://cloud.r -project.org/')
install.packages('fable  ',repos='https://cloud.r -project.org/')
install.packages('fable.prophet',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('fabletools',repos='https://cloud.r -project.org/')
install.packages('factorstochvol',repos='https://cloud.r -project.org/')
install.packages('fame',repos='https://cloud.r -project.org/')
install.packages('fanplot',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('fdaACF',repos='https://cloud.r -project.org/')
install.packages('feasts  ',repos='https://cloud.r -project.org/')
install.packages('FeedbackTS',repos='https://cloud.r -project.org/')
install.packages('fGarch',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('FinTS',repos='https://cloud.r -project.org/')
install.packages('FitAR',repos='https://cloud.r -project.org/')
install.packages('FitARMA',repos='https://cloud.r -project.org/')
install.packages('FKF',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('FKF.SP',repos='https://cloud.r -project.org/')
install.packages('fma',repos='https://cloud.r -project.org/')
install.packages('fNonlinear',repos='https://cloud.r -project.org/')
install.packages('ForeCA',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('forecast  ',repos='https://cloud.r -project.org/')
install.packages('ForecastComb',repos='https://cloud.r -project.org/')
install.packages('forecastHybrid',repos='https://cloud.r -project.org/')
install.packages('forecastML',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('FoReco',repos='https://cloud.r -project.org/')
install.packages('forecTheta',repos='https://cloud.r -project.org/')
install.packages('fpcb',repos='https://cloud.r -project.org/')
install.packages('fpp2',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('fpp3',repos='https://cloud.r -project.org/')
install.packages('fracdiff',repos='https://cloud.r -project.org/')
install.packages('fredr',repos='https://cloud.r -project.org/')
install.packages('freqdom',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('freqdom.fda',repos='https://cloud.r -project.org/')
install.packages('fsMTS',repos='https://cloud.r -project.org/')
install.packages('fts',repos='https://cloud.r -project.org/')
install.packages('ftsa',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('funtimes',repos='https://cloud.r -project.org/')
install.packages('garma',repos='https://cloud.r -project.org/')
install.packages('GAS',repos='https://cloud.r -project.org/')
install.packages('gdpc',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('ggdemetra',repos='https://cloud.r -project.org/')
install.packages('ggseas',repos='https://cloud.r -project.org/')
install.packages('glarma',repos='https://cloud.r -project.org/')
install.packages('GMDH',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('gmvarkit',repos='https://cloud.r -project.org/')
install.packages('GNAR',repos='https://cloud.r -project.org/')
install.packages('graphicalVAR',repos='https://cloud.r -project.org/')
install.packages('gratis',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('gravitas',repos='https://cloud.r -project.org/')
install.packages('greybox',repos='https://cloud.r -project.org/')
install.packages('gsarima',repos='https://cloud.r -project.org/')
install.packages('gsignal',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('gtop',repos='https://cloud.r -project.org/')
install.packages('HarmonicRegression',repos='https://cloud.r -project.org/')
install.packages('HDTSA',repos='https://cloud.r -project.org/')
install.packages('hht',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('hts',repos='https://cloud.r -project.org/')
install.packages('hwwntest',repos='https://cloud.r -project.org/')
install.packages('ifultools',repos='https://cloud.r -project.org/')
install.packages('imputePSF',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('imputeTestbench',repos='https://cloud.r -project.org/')
install.packages('imputeTS',repos='https://cloud.r -project.org/')
install.packages('IncDTW',repos='https://cloud.r -project.org/')
install.packages('influxdbr',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('InspectChangepoint',repos='https://cloud.r -project.org/')
install.packages('itsmr',repos='https://cloud.r -project.org/')
install.packages('KFAS',repos='https://cloud.r -project.org/')
install.packages('KFKSDS',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('kza',repos='https://cloud.r -project.org/')
install.packages('legion',repos='https://cloud.r -project.org/')
install.packages('locits',repos='https://cloud.r -project.org/')
install.packages('lomb',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('LongMemoryTS',repos='https://cloud.r -project.org/')
install.packages('LPStimeSeries',repos='https://cloud.r -project.org/')
install.packages('LSTS',repos='https://cloud.r -project.org/')
install.packages('ltsa',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('lubridate',repos='https://cloud.r -project.org/')
install.packages('MAPA',repos='https://cloud.r -project.org/')
install.packages('mAr',repos='https://cloud.r -project.org/')
install.packages('mar1s',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('MARSS',repos='https://cloud.r -project.org/')
install.packages('mbsts',repos='https://cloud.r -project.org/')
install.packages('mclcar',repos='https://cloud.r -project.org/')
install.packages('Mcomp',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('meboot',repos='https://cloud.r -project.org/')
install.packages('mfbvar',repos='https://cloud.r -project.org/')
install.packages('mFilter',repos='https://cloud.r -project.org/')
install.packages('mgm',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('mixAR',repos='https://cloud.r -project.org/')
install.packages('mlVAR',repos='https://cloud.r -project.org/')
install.packages('modeltime',repos='https://cloud.r -project.org/')
install.packages('modeltime.ensemble',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('mondate',repos='https://cloud.r -project.org/')
install.packages('mssm',repos='https://cloud.r -project.org/')
install.packages('MSwM',repos='https://cloud.r -project.org/')
install.packages('MTS',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('mtsdi',repos='https://cloud.r -project.org/')
install.packages('multDM',repos='https://cloud.r -project.org/')
install.packages('MultipleBubbles',repos='https://cloud.r -project.org/')
install.packages('multitaper',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('nardl',repos='https://cloud.r -project.org/')
install.packages('nets',repos='https://cloud.r -project.org/')
install.packages('NGSSEML',repos='https://cloud.r -project.org/')
install.packages('NlinTS',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('nlts',repos='https://cloud.r -project.org/')
install.packages('nnfor',repos='https://cloud.r -project.org/')
install.packages('nonlinearTseries',repos='https://cloud.r -project.org/')
install.packages('npst',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('nsarfima',repos='https://cloud.r -project.org/')
install.packages('NTS',repos='https://cloud.r -project.org/')
install.packages('odpc',repos='https://cloud.r -project.org/')
install.packages('onlineVAR',repos='https://cloud.r -project.org/')
install.packages('opera',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('otsad',repos='https://cloud.r -project.org/')
install.packages('paleoTS',repos='https://cloud.r -project.org/')
install.packages('partsm',repos='https://cloud.r -project.org/')
install.packages('pastecs',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('PCA4TS',repos='https://cloud.r -project.org/')
install.packages('pcdpca',repos='https://cloud.r -project.org/')
install.packages('pcts',repos='https://cloud.r -project.org/')
install.packages('pdc',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('pdfetch',repos='https://cloud.r -project.org/')
install.packages('perARMA',repos='https://cloud.r -project.org/')
install.packages('pomp',repos='https://cloud.r -project.org/')
install.packages('portes',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('ProbReco',repos='https://cloud.r -project.org/')
install.packages('prophet',repos='https://cloud.r -project.org/')
install.packages('psd',repos='https://cloud.r -project.org/')
install.packages('PSF',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('ptw',repos='https://cloud.r -project.org/')
install.packages('Quandl',repos='https://cloud.r -project.org/')
install.packages('quantspec',repos='https://cloud.r -project.org/')
install.packages('Rbeast',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('Rcatch22',repos='https://cloud.r -project.org/')
install.packages('readabs',repos='https://cloud.r -project.org/')
install.packages('regspec',repos='https://cloud.r -project.org/')
install.packages('RGENERATE',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('rhosa',repos='https://cloud.r -project.org/')
install.packages('RJDemetra',repos='https://cloud.r -project.org/')
install.packages('Rlgt',repos='https://cloud.r -project.org/')
install.packages('Rlibeemd',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('rmaf',repos='https://cloud.r -project.org/')
install.packages('RMAWGEN',repos='https://cloud.r -project.org/')
install.packages('robets',repos='https://cloud.r -project.org/')
install.packages('robfilter',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('RobKF',repos='https://cloud.r -project.org/')
install.packages('robustarima',repos='https://cloud.r -project.org/')
install.packages('roll',repos='https://cloud.r -project.org/')
install.packages('RSEIS',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('Rsfar',repos='https://cloud.r -project.org/')
install.packages('Rssa',repos='https://cloud.r -project.org/')
install.packages('RTransferEntropy',repos='https://cloud.r -project.org/')
install.packages('rts',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('rucrdtw',repos='https://cloud.r -project.org/')
install.packages('rugarch',repos='https://cloud.r -project.org/')
install.packages('runner',repos='https://cloud.r -project.org/')
install.packages('runstats',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('rwt',repos='https://cloud.r -project.org/')
install.packages('sazedR',repos='https://cloud.r -project.org/')
install.packages('scoringRules',repos='https://cloud.r -project.org/')
install.packages('scoringutils',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('SDD',repos='https://cloud.r -project.org/')
install.packages('sde',repos='https://cloud.r -project.org/')
install.packages('seas',repos='https://cloud.r -project.org/')
install.packages('season',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('seasonal',repos='https://cloud.r -project.org/')
install.packages('seasonalview',repos='https://cloud.r -project.org/')
install.packages('seer',repos='https://cloud.r -project.org/')
install.packages('Sim.DiffProc',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('sleekts',repos='https://cloud.r -project.org/')
install.packages('slider',repos='https://cloud.r -project.org/')
install.packages('smooth',repos='https://cloud.r -project.org/')
install.packages('smoots',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('sparsevar',repos='https://cloud.r -project.org/')
install.packages('spectral',repos='https://cloud.r -project.org/')
install.packages('spTimer',repos='https://cloud.r -project.org/')
install.packages('statespacer',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('stlplus',repos='https://cloud.r -project.org/')
install.packages('stochvol',repos='https://cloud.r -project.org/')
install.packages('stR',repos='https://cloud.r -project.org/')
install.packages('strucchange',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('strucchangeRcpp',repos='https://cloud.r -project.org/')
install.packages('stsm',repos='https://cloud.r -project.org/')
install.packages('sugrrants',repos='https://cloud.r -project.org/')
install.packages('surveillance',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('svars',repos='https://cloud.r -project.org/')
install.packages('sweep',repos='https://cloud.r -project.org/')
install.packages('sym.arma',repos='https://cloud.r -project.org/')
install.packages('synthesis',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('tbrf',repos='https://cloud.r -project.org/')
install.packages('Tcomp',repos='https://cloud.r -project.org/')
install.packages('tempdisagg',repos='https://cloud.r -project.org/')
install.packages('tensorTS',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('testcorr',repos='https://cloud.r -project.org/')
install.packages('tfarima',repos='https://cloud.r -project.org/')
install.packages('tframe',repos='https://cloud.r -project.org/')
install.packages('thief',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('Tides',repos='https://cloud.r -project.org/')
install.packages('tiger',repos='https://cloud.r -project.org/')
install.packages('timechange',repos='https://cloud.r -project.org/')
install.packages('timeDate',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('TimeProjection',repos='https://cloud.r -project.org/')
install.packages('timesboot',repos='https://cloud.r -project.org/')
install.packages('timeSeries',repos='https://cloud.r -project.org/')
install.packages('timeseriesdb',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('timetk',repos='https://cloud.r -project.org/')
install.packages('timsac',repos='https://cloud.r -project.org/')
install.packages('tis',repos='https://cloud.r -project.org/')
install.packages('tpr',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('trend',repos='https://cloud.r -project.org/')
install.packages('TSA',repos='https://cloud.r -project.org/')
install.packages('tsbox',repos='https://cloud.r -project.org/')
install.packages('TSclust',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('tscount',repos='https://cloud.r -project.org/')
install.packages('TSdbi',repos='https://cloud.r -project.org/')
install.packages('tsdecomp',repos='https://cloud.r -project.org/')
install.packages('tsdisagg2',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('TSdist',repos='https://cloud.r -project.org/')
install.packages('tsDyn',repos='https://cloud.r -project.org/')
install.packages('TSEntropies',repos='https://cloud.r -project.org/')
install.packages('tseries  ',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('tseriesChaos',repos='https://cloud.r -project.org/')
install.packages('tseriesEntropy',repos='https://cloud.r -project.org/')
install.packages('tsfeatures',repos='https://cloud.r -project.org/')
install.packages('tsfknn',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('tsibble  ',repos='https://cloud.r -project.org/')
install.packages('tsibbledata',repos='https://cloud.r -project.org/')
install.packages('tsibbletalk',repos='https://cloud.r -project.org/')
install.packages('tsintermittent',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('TSMining',repos='https://cloud.r -project.org/')
install.packages('tsModel',repos='https://cloud.r -project.org/')
install.packages('tsoutliers',repos='https://cloud.r -project.org/')
install.packages('tsPI',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('TSrepr',repos='https://cloud.r -project.org/')
install.packages('tsrobprep',repos='https://cloud.r -project.org/')
install.packages('TSstudio',repos='https://cloud.r -project.org/')
install.packages('TSTutorial',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('tsutils',repos='https://cloud.r -project.org/')
install.packages('tswge',repos='https://cloud.r -project.org/')
install.packages('UComp',repos='https://cloud.r -project.org/')
install.packages('urca',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('uroot',repos='https://cloud.r -project.org/')
install.packages('VAR.etp',repos='https://cloud.r -project.org/')
install.packages('VARDetect',repos='https://cloud.r -project.org/')
install.packages('vars',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('VARshrink',repos='https://cloud.r -project.org/')
install.packages('VARsignR',repos='https://cloud.r -project.org/')
install.packages('WaveletComp',repos='https://cloud.r -project.org/')
install.packages('wavelets',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('waveslim',repos='https://cloud.r -project.org/')
install.packages('wavethresh',repos='https://cloud.r -project.org/')
install.packages('wavScalogram',repos='https://cloud.r -project.org/')
install.packages('WeightedPortTest',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('wktmo',repos='https://cloud.r -project.org/')
install.packages('wwntests',repos='https://cloud.r -project.org/')
install.packages('x12',repos='https://cloud.r -project.org/')
install.packages('x12GUI',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('x13binary',repos='https://cloud.r -project.org/')
install.packages('xts',repos='https://cloud.r -project.org/')
install.packages('yuima',repos='https://cloud.r -project.org/')
install.packages('ZIM',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")

install.packages('zoo',repos='https://cloud.r -project.org/')
install.packages('ZRA',repos='https://cloud.r -project.org/')

require(unixtools)
path<-tempdir()
system(paste("rm -rf ", path, sep=""))
system("mkdir /tmp/new_tmp")
set.tempdir("/tmp/new_tmp")







