#!/bin/bash

Rscript binder/Rcpp_install.R

git clone --recursive https://github.com/s-u/unixtools.git unixtools
R CMD INSTALL unixtools

git clone --recursive https://github.com/sachsmc/ggkm.git
R CMD INSTALL ggkm

git clone --recursive https://github.com/benjaminrich/table1.git
R CMD INSTALL table1

git clone --recursive https://github.com/slowkow/ggrepel.git
R CMD INSTALL ggrepel

Rscript binder/install.R

echo "Sys.setenv(LD_LIBRARY_PATH=paste(Sys.getenv('JAVA_HOME'),'/server'))" > /srv/conda/envs/notebook/lib/R/etc/Rprofile.site
echo "Sys.setenv(RETICULATE_MINICONDA_ENABLED='FALSE')" >> /srv/conda/envs/notebook/lib/R/etc/Rprofile.site

###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

code-server --install-extension ms-python.python

pip install jupyterlab_latex
pip install tensorflow==2.5.0
pip install mimesis bokeh
pip install jupyterlab_latex
pip install radian
pip install tpot


###############################################################

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

# install JupyterLab extension
jupyter labextension install @jupyterlab/latex
jupyter labextension install dask-labextension
jupyter serverextension enable --py --sys-prefix dask_labextension
jupyter labextension install @jupyterlab/server-proxy

# jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build 
# jupyter labextension install beakerx-jupyterlab --no-build 
# jupyter labextension install @jupyterlab/git --no-build 
# jupyter serverextension enable --py jupyterlab_git
# jupyter labextension install jupyterlab_iframe --no-build 
# jupyter serverextension enable --py jupyterlab_iframe 
# jupyter labextension install jupyterlab-drawio --no-build 
# jupyter-nbextension install rise --py --sys-prefix
# jupyter-nbextension enable  rise --py --sys-prefix
# jupyter labextension install @jupyterlab/plotly-extension --no-build 
# jupyter labextension install jupyterlab-plotly --no-build 
# jupyter labextension install @jupyterlab/toc --no-build 

# Building everything up

jupyter lab build

###########################
# hadoop related commands #
###########################

# creating ssh-related folders
mkdir .ssh/etc/ssh -p


# setup passphraseless ssh (forcing the adding to know hosts)
ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa  &&   cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && chmod 0600 ~/.ssh/authorized_keys 

# generating keys for sshd server
ssh-keygen -A -f .ssh 
chmod 600 .ssh/etc/ssh/* -R

# set env var for java
echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 " >> ~/.bashrc
echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 " >> ~/.profile

# hadoop 3.*.*
echo "export PDSH_RCMD_TYPE=ssh" >> ~/.bashrc